name: deploy dist

on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: installing node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: printe the version
        run: node -v

      - name: installing dependencies
        run: npm ci

      # run: |
      #   echo "git cloning.."
      #   echo "${{toJson(github)}}"
      #   git clone https://github.com/${{github.repository}}.git
